apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.orgname }}-cli-claim0
  name: {{ .Values.orgname }}-cli-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
status: {}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.orgname }}-cli-claim1
  name: {{ .Values.orgname }}-cli-claim1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
status: {}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.orgname }}-cli
  name: {{ .Values.orgname }}-cli
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
status: {}
