apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.domain }}
  name: {{ .Values.domain }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: {{ .Values.domain }}
    spec:
      containers:
      - args:
        - orderer
        env:
        - name: ORDERER_GENERAL_GENESISFILE
          value: {{ .Values.env.ORDERER_GENERAL_GENESISFILE }}
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: {{ .Values.env.ORDERER_GENERAL_GENESISMETHOD }}
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: {{ .Values.env.ORDERER_GENERAL_LISTENADDRESS }}
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: {{ .Values.env.ORDERER_GENERAL_LOCALMSPDIR }}
        - name: ORDERER_GENERAL_LOCALMSPID
          value: {{ .Values.env.ORDERER_GENERAL_LOCALMSPID }}
        - name: FABRIC_LOGGING_SPEC
          value: {{ .Values.env.FABRIC_LOGGING_SPEC }}
        - name: ORDERER_GENERAL_TLS_CERTIFICATE
          value: {{ .Values.env.ORDERER_GENERAL_TLS_CERTIFICATE }}
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "{{ .Values.env.ORDERER_GENERAL_TLS_ENABLED }}"
        - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          value: {{ .Values.env.ORDERER_GENERAL_TLS_PRIVATEKEY }}
        - name: ORDERER_GENERAL_TLS_ROOTCAS
          value: "{{ .Values.env.ORDERER_GENERAL_TLS_ROOTCAS }}"
        - name: ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR
          value: "{{ .Values.env.ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR }}"
        - name: ORDERER_KAFKA_VERBOSE
          value: "{{ .Values.env.ORDERER_KAFKA_VERBOSE }}"
        - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
          value: "{{ .Values.env.ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE }}"
        - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
          value: "{{ .Values.env.ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY }}"
        - name: ORDERER_GENERAL_CLUSTER_ROOTCAS
          value: "{{ .Values.env.ORDERER_GENERAL_CLUSTER_ROOTCAS }}"
        # - name: CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE
        #   value: bridge
        # - name: CORE_VM_ENDPOINT
        #   value: unix:///host/var/run/docker.sock
        # - name: GODEBUG
        #   value: netdns=go
        image: hyperledger/fabric-orderer:1.4.1
        name: {{ .Values.domain }}
        ports:
        - containerPort: 7050
        resources: {}
        volumeMounts:
        - mountPath: /var/hyperledger/orderer
          name: "{{ .Values.domain }}-claim0"
        - mountPath: /var/hyperledger/production/orderer
          name: "{{ .Values.domain }}"
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric
      restartPolicy: Always
      volumes:
      - name: "{{ .Values.domain }}-claim0"
        persistentVolumeClaim:
          claimName: "{{ .Values.domain }}-claim0"
      - name: "{{ .Values.domain }}"
        persistentVolumeClaim:
          claimName: "{{ .Values.domain }}"
status: {}
