# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "example-ecosystem.fullname" . }}
#   labels:
#     app: {{ include "example-ecosystem.name" . }}
#     chart: {{ include "example-ecosystem.chart" . }}
#     release: {{ .Release.Name }}
#     heritage: {{ .Release.Service }}
# spec:
#   type: {{ .Values.service.type }}
#   ports:
#     - port: {{ .Values.service.port }}
#       targetPort: http
#       protocol: TCP
#       name: http
#   selector:
#     app: {{ include "example-ecosystem.name" . }}
#     release: {{ .Release.Name }}
